import { readFile, readdir } from "node:fs/promises";
import { basename, join } from "node:path";
import {
  FEDRAMP_SCHEMA_PINS,
  loadPinnedSchema,
  validateAgainst,
  type SchemaViolation,
} from "./fedramp-schemas.js";
import { OCR_ARTIFACT, PACKAGE_OVERVIEW_ARTIFACT } from "./fedramp-exports.js";
import { SDR_ARTIFACT } from "./sdr-build.js";

// The package conformance check (plan Q5.2 — G10, `FRC-CSO-JSN`): certification
// JSON validated against the pinned FedRAMP schemas, as a check over documents
// ON DISK rather than as a side effect of generating them.
//
// WHY THIS IS A COMMAND AND NOT A FLAG ON `exports`. G10 is "certification JSON
// not matching FedRAMP schemas", and the document in front of a provider is
// usually one they already have — written by another tool, edited by hand, or
// generated by a rampscan that predates the current pins. `exports` can only
// ever check the bytes it just produced, which is the one case where the answer
// was never in doubt. This reads a file.
//
// THREE THINGS IT CHECKS, AND THE SECOND IS THE POINT.
//
//   1. The document validates against its pinned schema. (`loadPinnedSchema`
//      independently re-checks the schema's own bytes and version, so a drifted
//      vendored schema fails here before any document is judged.)
//   2. THE DOCUMENT'S OWN STAMP AGREES WITH A FRESH VALIDATION. A file carrying
//      `x-rampscan.conformance.valid: true` that does not validate is a worse
//      fact than a file with no stamp: it is a document whose self-description
//      is false, which is what an assessor would be reading. It happens
//      honestly — the pins moved under a document generated months ago — and it
//      must never pass quietly.
//   3. The stamp names the schema this checkout pins for that file. A document
//      stamped against a version we no longer pin is reported as such rather
//      than silently re-judged, because "valid" and "valid against what" are
//      different answers.
//
// AND IT FAILS CLOSED, the same direction as the validator it calls: a document
// whose schema cannot be resolved is an exit, never a skip. A conformance
// checker that quietly ignored the file it did not recognise would report a
// clean directory it never read.

/** The filenames rampscan itself writes, mapped to the schema that gates each. */
const KNOWN_ARTIFACTS: Readonly<Record<string, string>> = {
  [PACKAGE_OVERVIEW_ARTIFACT]: "fedramp-certification-package-overview-schema-2026-06-24.json",
  [OCR_ARTIFACT]: "fedramp-ongoing-certification-report-schema-2026-06-24.json",
  [SDR_ARTIFACT]: "fedramp-security-decision-record-schema-2026-06-24.json",
};

export interface ConformanceFinding {
  path: string;
  /** the pinned schema the document was judged against */
  schemaFile: string;
  schemaVersion: string;
  /** how the schema was chosen — a reader should never have to guess */
  schemaSource: "--schema" | "x-rampscan stamp" | "filename";
  violations: SchemaViolation[];
  /**
   * The document claimed a conformance verdict that this run disagrees with.
   * Absent when the document carries no stamp — an unstamped document is not a
   * lying one.
   */
  stampDisagreement?: string;
  conformant: boolean;
}

export interface ConformanceResult {
  findings: ConformanceFinding[];
  conformant: boolean;
}

function stampOf(document: unknown): Record<string, unknown> | undefined {
  if (document === null || typeof document !== "object") return undefined;
  const ext = (document as Record<string, unknown>)["x-rampscan"];
  if (ext === null || typeof ext !== "object") return undefined;
  const stamp = (ext as Record<string, unknown>)["conformance"];
  if (stamp === null || typeof stamp !== "object") return undefined;
  return stamp as Record<string, unknown>;
}

/**
 * Which pinned schema gates this document. An explicit `--schema` wins, then
 * the document's own stamp, then the filename rampscan writes. None of the
 * three is a guess at the document's SHAPE: inferring a schema from the fields
 * present would pick the schema a malformed document happens to look like,
 * which is the one question a conformance check must not answer for itself.
 */
export function resolveSchema(
  path: string,
  document: unknown,
  override?: string,
): { schemaFile: string; schemaSource: ConformanceFinding["schemaSource"] } {
  if (override !== undefined) {
    if (FEDRAMP_SCHEMA_PINS[override] === undefined) {
      throw new Error(
        `--schema ${override} is not a pinned FedRAMP schema. Pinned: ${Object.keys(FEDRAMP_SCHEMA_PINS).join(", ")}`,
      );
    }
    return { schemaFile: override, schemaSource: "--schema" };
  }

  const stamped = stampOf(document)?.["schema"];
  if (typeof stamped === "string") {
    if (FEDRAMP_SCHEMA_PINS[stamped] === undefined) {
      throw new Error(
        `${path} is stamped against ${stamped}, which this checkout does not pin — the document was generated against a different schema version and re-judging it against ours would answer a question nobody asked. Name the pinned schema with --schema to check it anyway`,
      );
    }
    return { schemaFile: stamped, schemaSource: "x-rampscan stamp" };
  }

  const known = KNOWN_ARTIFACTS[basename(path)];
  if (known !== undefined) return { schemaFile: known, schemaSource: "filename" };

  throw new Error(
    `cannot tell which FedRAMP schema ${path} should be judged against: it carries no \`x-rampscan.conformance.schema\` stamp and its name is not one rampscan writes. Name one with --schema — a conformance check that skipped the file it did not recognise would report a clean directory it never read`,
  );
}

async function checkOne(
  schemaRoot: string,
  path: string,
  override?: string,
): Promise<ConformanceFinding> {
  const document = JSON.parse(await readFile(path, "utf8")) as unknown;
  const { schemaFile, schemaSource } = resolveSchema(path, document, override);
  const pin = FEDRAMP_SCHEMA_PINS[schemaFile];
  if (pin === undefined) throw new Error(`${schemaFile} is not pinned`);

  // loads, and re-verifies the schema's bytes and version against the pins
  const loaded = await loadPinnedSchema(schemaRoot, schemaFile);
  const violations = validateAgainst(loaded, document);

  const finding: ConformanceFinding = {
    path,
    schemaFile,
    schemaVersion: pin.schemaVersion,
    schemaSource,
    violations,
    conformant: violations.length === 0,
  };

  const stamp = stampOf(document);
  if (stamp !== undefined) {
    const claimed = stamp["valid"];
    const claimedVersion = stamp["schemaVersion"];
    if (typeof claimed === "boolean" && claimed !== (violations.length === 0)) {
      finding.stampDisagreement = claimed
        ? `the document stamps itself conformant and it is not — ${violations.length} violation(s) against ${schemaFile} @ ${pin.schemaVersion}. A document whose self-description is false is worse than one with no stamp, because the self-description is what a reader trusts. Regenerate it with \`rampscan exports\``
        : `the document stamps itself NONconformant and it validates clean against ${schemaFile} @ ${pin.schemaVersion} — the stamp predates a fix, or the pins moved. Regenerate it so the file agrees with itself`;
      finding.conformant = false;
    } else if (typeof claimedVersion === "string" && claimedVersion !== pin.schemaVersion) {
      finding.stampDisagreement = `the document was judged against ${schemaFile} @ ${claimedVersion} and this checkout pins @ ${pin.schemaVersion} — the verdict above is this checkout's, not the one in the file. Regenerate it`;
      finding.conformant = false;
    }
  }

  return finding;
}

export interface ConformanceInput {
  /** the rampscan checkout — where the PINNED schemas live */
  schemaRoot: string;
  /** a file, or a directory whose `*.json` documents are all checked */
  target: string;
  /** force a pinned schema rather than resolving one per document */
  schema?: string;
}

export async function checkConformance(input: ConformanceInput): Promise<ConformanceResult> {
  let paths: string[];
  try {
    const entries = await readdir(input.target, { withFileTypes: true });
    paths = entries
      .filter((e) => e.isFile() && e.name.endsWith(".json"))
      .map((e) => join(input.target, e.name))
      .sort();
    if (paths.length === 0) {
      throw new Error(
        `${input.target} holds no JSON document to check. An empty exports directory is not a passing conformance check — run \`rampscan exports\` first`,
      );
    }
  } catch (cause) {
    // ENOTDIR means it is the file itself, which is a target, not an error
    if ((cause as NodeJS.ErrnoException).code !== "ENOTDIR") throw cause;
    paths = [input.target];
  }

  const findings: ConformanceFinding[] = [];
  for (const path of paths) {
    findings.push(await checkOne(input.schemaRoot, path, input.schema));
  }
  return { findings, conformant: findings.every((f) => f.conformant) };
}

/** The terminal reading. Every document named, conformant or not — a check that printed only failures would leave a reader unable to tell "clean" from "never ran". */
export function renderConformance(result: ConformanceResult): string {
  const lines: string[] = [];
  for (const f of result.findings) {
    const verdict = f.conformant
      ? "conformant"
      : f.violations.length > 0
        ? `${f.violations.length} VIOLATION(S)`
        : "STAMP DISAGREES";
    lines.push(`${f.path} → ${verdict}  (${f.schemaFile} @ ${f.schemaVersion}, via ${f.schemaSource})`);
    for (const v of f.violations) {
      lines.push(`    ✗ ${v.path === "" ? "<root>" : v.path}: ${v.message}`);
    }
    if (f.stampDisagreement !== undefined) lines.push(`    ! ${f.stampDisagreement}`);
  }
  lines.push(
    "",
    result.conformant
      ? `FRC-CSO-JSN: ${result.findings.length} document(s) conform to the pinned FedRAMP schemas`
      : `FRC-CSO-JSN: ${result.findings.filter((f) => !f.conformant).length} of ${result.findings.length} document(s) do not conform`,
  );
  return lines.join("\n");
}
