import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { ScanResult } from "@rampscan/schema";
import type { RecipeResult } from "@rampscan/schema";

// `rampscan report` (plan G3): docs/FRONTIER-PIPELINE.md generated from a
// real run. The ramprules house rule, inherited: every number in the output
// is computed from the scan result it cites — never typed. The founding
// doc's closing test, executed: pointed at its own repo, does the board
// come back worth reading?

export interface ReportOptions {
  /** scan-result.json to report from */
  resultPath: string;
  /** where the markdown lands */
  outPath: string;
}

function ksiThemeOf(ksiId: string): string {
  // "KSI-SVC-01" → "KSI-SVC"
  return ksiId.split("-").slice(0, 2).join("-");
}

function controlFamilyOf(controlId: string): string {
  // "ac-2.1" → "ac"
  return controlId.split("-")[0] ?? controlId;
}

function distinct<T>(values: T[]): T[] {
  return [...new Set(values)];
}

function recipeTable(rows: RecipeResult[], withReason: boolean): string[] {
  const lines = withReason
    ? ["| recipe | collector | KSIs | controls | why |", "|---|---|---|---|---|"]
    : ["| recipe | collector | KSIs | controls | assertions |", "|---|---|---|---|---|"];
  for (const row of rows) {
    const ksis = row.ksi_ids.join(", ");
    const controls = row.control_ids.join(", ");
    if (withReason) {
      lines.push(
        `| \`${row.recipe_id}\` | ${row.collector} | ${ksis} | ${controls} | ${row.reason ?? "—"} |`,
      );
    } else {
      const passed = row.assertions.filter((a) => a.passed).length;
      lines.push(
        `| \`${row.recipe_id}\` | ${row.collector} | ${ksis} | ${controls} | ${passed}/${row.assertions.length} passed |`,
      );
    }
  }
  return lines;
}

/** Pure: scan result → the FRONTIER-PIPELINE.md content. */
export function generateFrontierReport(result: ScanResult): string {
  const byVerdict = (verdict: RecipeResult["verdict"]) =>
    result.recipes
      .filter((r) => r.verdict === verdict)
      .sort((a, b) => a.recipe_id.localeCompare(b.recipe_id));
  const evidenced = byVerdict("evidenced");
  const violated = byVerdict("violated");
  const unevidenced = byVerdict("unevidenced");

  // recounted from the rows, not read from the summary — the generator
  // trusts nothing it can recompute
  const total = result.recipes.length;
  const covered = [...evidenced, ...violated];
  const ksisCovered = distinct(covered.flatMap((r) => r.ksi_ids)).sort();
  const ksisAll = distinct(result.recipes.flatMap((r) => r.ksi_ids)).sort();
  const controlsCovered = distinct(covered.flatMap((r) => r.control_ids)).sort();
  const controlsAll = distinct(result.recipes.flatMap((r) => r.control_ids)).sort();
  const themes = distinct(result.recipes.flatMap((r) => r.ksi_ids.map(ksiThemeOf))).sort();
  const families = distinct(result.recipes.flatMap((r) => r.control_ids.map(controlFamilyOf))).sort();

  const themeRows = themes.map((theme) => {
    const of = (rows: RecipeResult[]) =>
      rows.filter((r) => r.ksi_ids.some((k) => ksiThemeOf(k) === theme)).length;
    return `| ${theme} | ${of(evidenced)} | ${of(violated)} | ${of(unevidenced)} |`;
  });

  const toolRows = Object.entries(result.tool_versions)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([collector, version]) => `| ${collector} | ${version} |`);

  const skippedRows = result.skipped_collectors.map((s) => `| ${s.collector} | ${s.reason} |`);

  const lines: string[] = [
    "# rampscan — frontier pipeline",
    "",
    `**Generated by \`rampscan report\` from run \`${result.run_id}\` — every number below is computed from that run, never typed.**`,
    "",
    `- **repo:** \`${result.repo}\``,
    `- **commit:** \`${result.commit}\``,
    `- **scanned:** ${result.timestamp}`,
    `- **dataset:** \`${result.dataset_version}\``,
    "",
    "## The three registers",
    "",
    `Of **${total}** pipeline recipes: **${evidenced.length} evidenced**, **${violated.length} violated**, **${unevidenced.length} unevidenced** — the honest default: what nobody evidenced stays visible.`,
    "",
    `Coverage reaches **${ksisCovered.length} of ${ksisAll.length}** recipe-mapped KSIs and **${controlsCovered.length} of ${controlsAll.length}** recipe-mapped controls, across ${themes.length} KSI themes (${themes.join(", ")}) and ${families.length} control families (${families.join(", ")}).`,
    "",
  ];

  if (evidenced.length > 0) {
    lines.push(`### Evidenced (${evidenced.length})`, "", ...recipeTable(evidenced, false), "");
  }
  if (violated.length > 0) {
    lines.push(`### Violated (${violated.length})`, "", ...recipeTable(violated, false), "");
  }
  if (unevidenced.length > 0) {
    lines.push(`### Unevidenced (${unevidenced.length})`, "", ...recipeTable(unevidenced, true), "");
  }

  lines.push(
    "## Coverage by KSI theme",
    "",
    "| theme | evidenced | violated | unevidenced |",
    "|---|---|---|---|",
    ...themeRows,
    "",
    "## Provenance",
    "",
    "| collector | tool version |",
    "|---|---|",
    ...toolRows,
    "",
  );
  if (skippedRows.length > 0) {
    lines.push(
      "### Skipped collectors",
      "",
      "| collector | reason |",
      "|---|---|",
      ...skippedRows,
      "",
    );
  }
  lines.push(
    "## Reproduce",
    "",
    "```sh",
    `pnpm rampscan scan ${result.repo}`,
    "pnpm rampscan report",
    "```",
    "",
    `Findings this run: ${result.findings.length}. Verdicts cite recipe, KSI, and control IDs that resolve against dataset \`${result.dataset_version}\`.`,
    "",
  );
  return lines.join("\n");
}

export async function report(options: ReportOptions): Promise<{ outPath: string; lines: string[] }> {
  const resultPath = resolve(options.resultPath);
  const outPath = resolve(options.outPath);
  const result = ScanResult.parse(JSON.parse(await readFile(resultPath, "utf8")));
  await writeFile(outPath, generateFrontierReport(result));
  return {
    outPath,
    lines: [
      `frontier report: ${outPath}`,
      `from run ${result.run_id} @ ${result.commit.slice(0, 12)} (${result.recipes.length} recipes)`,
    ],
  };
}
